# frozen_string_literal: true

# One row of the purification (تطهير) list: a parcel of shares held during one
# calendar quarter. Generated by LotLedger.generate_purifications! (never edited
# by hand, apart from the paid flags).
#
#   * CLOSED  row (sell_transaction_id present): shares sold in this quarter.
#             Carries the S&P purification (percentage x profit, if any).
#   * ONGOING row (sell_transaction_id nil): shares still held at quarter end;
#             carried into the next quarter as a new row.
#
# Every row carries the AAOIFI purification (quantity x days x per-day rate).
# AAOIFI and S&P each have their own paid flag.
class PurificationEntry < ApplicationRecord
  include TenantScoped
  tenant_through :portfolio

  KINDS = %w[aaoifi sp].freeze

  belongs_to :portfolio
  belongs_to :asset
  belongs_to :asset_lot
  belongs_to :sell_transaction, class_name: "PortfolioTransaction", optional: true

  validates :quarter, :period_start, :period_end, :quantity, presence: true
  validates :quarter, format: { with: LotLedger::Purification::QUARTER_LABEL }

  scope :for_quarter, ->(quarter) { where(quarter: quarter) }
  scope :closed, -> { where.not(sell_transaction_id: nil) }
  scope :ongoing, -> { where(sell_transaction_id: nil) }
  scope :chronological, -> { order(:period_start, :asset_lot_id, :sell_transaction_id) }

  def closed?
    sell_transaction_id.present?
  end

  def ongoing?
    !closed?
  end

  def in_progress?
    quarter == LotLedger::Purification.quarter_label(Date.current)
  end

  # --- amounts per kind --------------------------------------------------------

  def amount_for(kind)
    kind.to_s == "sp" ? sp_amount.to_d : aaoifi_amount.to_d
  end

  def paid?(kind)
    kind.to_s == "sp" ? sp_paid : aaoifi_paid
  end

  def total_amount
    aaoifi_amount.to_d + sp_amount.to_d
  end

  # --- spreadsheet-style derived columns (closed rows only) ---------------------

  def cost
    buy_price_per_unit.to_d * quantity.to_d
  end

  def profit
    return unless closed?

    (sell_price_per_unit.to_d - buy_price_per_unit.to_d) * quantity.to_d
  end

  def profit_after_purification
    return unless closed?

    profit - total_amount
  end

  def profit_after_purification_pct
    return unless closed? && cost.positive?

    profit_after_purification / cost
  end

  def purification_pct_of_profit
    return unless closed? && profit.nonzero?

    total_amount / profit
  end

  def purification_pct_of_cost
    return unless closed? && cost.positive?

    total_amount / cost
  end
end
